# Main configuration file for your Quarto blog
project:
  type: website
  output-dir: posts

website:
  title: "My Markets Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home

    right:
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/Kaistxr
      - icon: linkedin
        href: https://www.linkedin.com/in/kai-larsen-pugh/
  page-footer:
    left: "Blog made with Quarto"
    right:
      - icon: github
        href: https://github.com/Kaistxr

format:
  html:
    theme: zephyr
    css: styles.css
    mainfont: "Inter"
    html-math-method: mathjax
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com">
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&display=swap" rel="stylesheet">

editor: visual
